# Generated by Django 4.2.19 on 2025-03-18 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
