# Generated by Django 4.2.19 on 2025-03-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='Not specified', max_length=255),
        ),
    ]
