# Generated by Django 4.2.19 on 2025-03-31 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.TextField(default='Enter category'),
        ),
    ]
